sudo: required
addons:
  chrome: stable
language: node_js
node_js:
  - "10.16.0"
branches:
  only:
    - master
before_script:
  - npm install -g @angular/cli
script:
  - ng test --no-watch --no-progress --browsers=ChromeHeadlessCI
  - npm install
  - ng build
deploy:
  skip_cleanup: true
  provider: firebase
  token:
    secure: $FIREBASE_TOKEN